# Generated by Django 4.2.4 on 2023-11-19 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cerveza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('alcohol', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Alcohol')),
                ('ibu', models.IntegerField(verbose_name='Ibu')),
                ('tapa', models.ImageField(blank=True, null=True, upload_to='assets/tapas/', verbose_name='Tapa')),
                ('botella', models.ImageField(blank=True, null=True, upload_to='assets/botellas/', verbose_name='Botella')),
                ('tipo', models.CharField(max_length=3, verbose_name='Tipo')),
                ('stock', models.IntegerField(default=0, null=True, verbose_name='Stock')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='Dni')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nickname')),
                ('password', models.CharField(max_length=45, verbose_name='Pass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cualidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cualidad', models.CharField(max_length=50, verbose_name='Tipo')),
            ],
        ),
        migrations.CreateModel(
            name='IngresoInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de ingreso')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('cerveza', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.cerveza')),
            ],
        ),
        migrations.CreateModel(
            name='Proovedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='Dni')),
                ('empresa', models.CharField(max_length=50, verbose_name='Empresa')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
                ('telefono', models.CharField(max_length=15, verbose_name='Telefono')),
                ('cerveza', models.ManyToManyField(through='core.IngresoInsumos', to='core.cerveza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ingresoinsumos',
            name='proovedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.proovedor'),
        ),
        migrations.AddField(
            model_name='cerveza',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='cerveza',
            name='cualidades',
            field=models.ManyToManyField(to='core.cualidad', verbose_name='Cualidades'),
        ),
    ]
