# Generated by Django 4.2.4 on 2023-10-24 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='nobre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='proovedor',
            old_name='nobre',
            new_name='nombre',
        ),
    ]
