INSERT INTO public.core_cerveza (marca, descripcion, alcohol, ibu, tapa, botella, tipo, stock)
VALUES ('Black Horse Ale','Existen muchas cervezas doradas y refrescantes. Pero frutadas y con destellos finales de lúpulo, sólo hay un estilo: la legendaria Black Horse Ale. En Brewery rescatamos la antigua receta de la cerveza favorita de los bebedores en Toronto, Canada, y la honramos desde 1983. En nuestra cocina, su legado sigue intacto.',5,22,'assets/tapas/tapa-black-horse.png','assets/botellas/botella-black-horse.jpg','RUB',0),
       ('Branding Ale','Este tipo de cervezas artesanales se fermentan a temperaturas superiores a las de las Lager (hasta los 25ºC). Son muy aromáticas, dulces, con cuerpo y generalmente con sabor muy marcado.',4.5,25,'assets/tapas/tapa-branding-ale.png','assets/botellas/botella-branding-ale.jpg','RUB',0),
       ('Light Beer','Es una cerveza demasiado simple, a veces indistinguible del agua, es para aquellas personas que se ponen en pedo con exagerada facilidad. Su nombre describe su principal facultad, es Light en todo sentido y forma.',3,12,'assets/tapas/tapa-ligth-beer.png','assets/botellas/botella-ligth-beer.jpg','RUB',0),
       ('Labbatt Legere Light','Una cerveza francesa que fue el experimento fallido de alguien que intento hacer vino con malta, creo una cerbeza absurdamente amarga y con el dulzor que le proporciona el delicado proceso de fermentacion del vino',4,85,'assets/tapas/tapa-labbat.png','assets/botellas/botella-labbat.jpg','RUB',0),
       ('Heidelberg','Nuestra cerveza de mayor graduación alcohólica. Una hermandad de malta y licor, con rasgos de nuez, caramelo y dulce de leche. Heidelberg fue creada en 1976 en Vancouver, Canada y la producimos segun la receta original.',19,53,'assets/tapas/tapa-heidelberg.png','assets/botellas/botella-helderberg.jpg','ROJ',0),
       ('Extra Old Stock','Antiguamente los procesos de elaboracion de cerbeza eran muy rudimentarios, no existian las recetas de elaboracion de cerbeza que utilizamos actualmente. Esta cerbeza sigue la misma elaboracion de la vieja escuela, su elaboracion tan "a ojo" hace que sea tan especial para nosotros, ya que su elaboracion sigue el mismo proceso que utilizaba el fundador de Brewery, en los años 1735.',6.2,87,'assets/tapas/tapa-extra-old-stock.png','assets/botellas/botella-extra-old-stock.jpg','ROJ',0),
       ('Molson Bock','Como el caracter de un carnero montañes, la cerveza Molson te va a meter un cabesazo que te va a dejar sentado un buen rato, para que puedas seguir degustando de esta extravagante cerveza traida de los Aples Suizos.',5,27,'assets/tapas/tapa-molson-bock.png','assets/botellas/botella-molson-bock.jpg','ROJ',0),
       ('Super Bock','Durante más de setecientos años, la llegada de la primavera se ha celebrado en una gran tradición europea, la elaboración de la cerveza Bock. Super Bock de Labatt se ha elaborado para reconocer esta feliz tradición. Es suave y delicioso... un producto de primera calidad elaborado especialmente para celebrar la llegada de la primavera. Super Bock Elaborado para celebrar la llegada de la primavera.',14,15,'assets/tapas/tapa-super-bock.png','assets/botellas/botella-super-bock.jpg','ROJ',0),
       ('Spar 6 Malt Liquor','Una cerveza creada por una tribu al norte de una isla de centroamerica, tiene un sabor extraño y dulce, algunos criticos afirman que es elaborada con agua de rio sin pasteurizar y desde Brewery confirmamos que es totalmente cierto.',6,8,'assets/tapas/tapa-spar6.png','assets/botellas/botella-spar6.jpg','ROJ',0),
       ('Labbat''s IPA','De Inglaterra a India hay un largo recorrido. En 1780, Mr. Hodgson descubrió que elevando el lúpulo y la graduación alcohólica, la cerveza llegaba a destino intacta. Bautizó a su fórmula India Pale Ale. En Brewery, le sumamos lúpulos americanos con presencia de flores y cítricos. Nuestra cerveza viajera.',6.6,58,'assets/tapas/tapa-labbat-ipa.png','assets/botellas/botella-labbat-ipa.jpg','ROJ',0),
       ('Dow Cream Porter Breweries','Es una cerveza negra de origen irlandés. En ella se descubren sabores de chocolate y nueces en el paladar, con un licoroso y placentero post-gusto. Muy corpulenta, de espuma cremosa e increíblemente fácil de tomar debido a que posee menos gas carbónico que las cervezas tradicionales.',4.9,35,'assets/tapas/tapa-porter.png','assets/botellas/botella-porter.jpg','NEG',0),
       ('Duffy''s Stoutg','Elaborada con maltas tostadas y matices de cafe y nuez, te deja la lengua seca como pechuga de pavo al horno, la cerveza es tan negra que vuelve el cristal de la botella totalmente opaco, su receta fue creada por una petrolera que utilizaba uno de sus destiladores de petroleo para destilar alcohol.',12,52,'assets/tapas/tapa-duffy-stout.png','assets/botellas/botella-duffy-stout.jpg','NEG',0),
       ('Guinness Extra Stout','Catalina la Grande amaba las emociones fuertes. Por eso, la Guinness Stout, negra y tostada, empapada de alcohol y pasas, amarga y ahumada, era su cerveza favorita. Esencia inglesa de exportación. Tímidos, abstenerse.',8.5,49,'assets/tapas/tapa-guiness.png','assets/botellas/botella-guiness.jpg','NEG',0),
       ('Silver Spring Extra Stout','Esta receta sigue la misma tradicion de Labatt con sus cervezas frutadas y aromaticas, pero con la diferencia de que esta cerveza es negra y tiene olor a bodega y a humedad, se deduce que es un lote de cervezas que Labatt se olvido de exportar y por alguna razon se puso negra, su misterio y escacez la hace tan deliciosa.',10,55,'assets/tapas/tapa-silver-spring.png','assets/botellas/botella-silver-spring.jpg','NEG',0),
       ('Moosehead London Stout','Una edicion especial de cerveza Inglesa, en su simpleza se esconde su elegancia y minimalismo, basicamente es una cerveza elaborada con malta tostada y nada mas, se suelen detectar aromas con tonalidad a cafe y nuez, ligeros maticez de cascara de naranja y corteza de roble, pero no tiene nada mas que malta tostada y agua de la canilla en su elaboracion.',5,12,'assets/tapas/tapa-london-stout.png','assets/botellas/botella-london-stout.jpg','NEG',0),
       ('Champlain Portery','En la profunda tristeza que oculta tu sombra marchándose, el sonido seco de un portazo y ciegas palabras que confirman el adiós de tu mirada. Se hace pequeña y se va, tu sombra, tu figura... Esa sensación de vacío, de terror, cesa el efecto hasta del más fuerte alcohol para gritarte... Perdón.',17,58,'assets/tapas/tapa-champlain.png','assets/botellas/botella-champlain.jpg','NEG',0);

INSERT INTO public.core_cerveza_cualidades (cerveza_id, cualidad_id)
VALUES
(3,1),
(3,2),
(3,3),
(4,5),
(4,6),
(4,7),
(5,8),
(5,9),
(5,2),
(6,23),
(6,18),
(6,10),
(7,14),
(7,19),
(7,26),
(7,21),
(8,14),
(8,13),
(8,28),
(9,12),
(9,24),
(9,25),
(10,23),
(10,31),
(10,16),
(11,12),
(11,6),
(11,37),
(12,11),
(12,10),
(12,5),
(12,17),
(13,32),
(13,20),
(13,22),
(14,35),
(14,15),
(14,38),
(15,32),
(15,26),
(15,27),
(15,28),
(16,33),
(16,17),
(16,40),
(16,28),
(17,33),
(17,39),
(17,29),
(18,32),
(18,34),
(18,36);

    